export const FETCH_CREATURES = 'FETCH_CREATURES';
export const FILTER_CREATURES = 'FILTER_CREATURES';
export const FILTER_CHARACTERS = 'FILTER_CHARACTERS';
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const SHOW_OPTIONS = 'SHOW_OPTIONS';
export const SELECT_OPTION = 'SELECT_OPTION';
export const FETCH_CREATURE_BY_ID = 'FETCH_CREATURE_BY_ID';
